### PR TITLE
Fix interaction storage API

### LINKED ISSUE #46: Fix API for storing credentials on the InteractionManager
### Scope of the feature

The `CredentialOfferFlow` state structure was changed, making the storage utils (`interaction.ts`) outdated. 

### Tasks 
- [ ] change the storage API from the Interaction class
- [ ] rename `flowType`'s CredentialReceive to CredentialOffer

### PR DESCRIPTION
**Pull request by clauxx**
closes #46

### CODE REVIEW

File: src/lib/interactionManager/interaction.ts [hunk 1]
```diff
@@ -292,21 +294,40 @@ export class Interaction {
     }
   }
 
-  public async storeCredential(toSave: SignedCredentialWithMetadata[]) {
+  public storeSelectedCredentials() {
```
Comment (mnzaki) [inline src/lib/interactionManager/interaction.ts:297]: These two methods (`storeSelectedCredentials` and `storeCredentialMetadata`) are missing some error checking.
At least check that it is in fact a `CredentialOfferFlow`
And also check that the state has the necessary data (maybe the flow isn't through yet?)
